apiVersion: v1
kind: Service
metadata:
  name: trend-store-service
  namespace: test
spec:
  selector:
    app: trend-store
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
